./run.sh test_data/jnh/jnh20.cnf
./run.sh test_data/jnh/jnh307.cnf
./run.sh test_data/jnh/jnh219.cnf
./run.sh test_data/jnh/jnh16.cnf
./run.sh test_data/jnh/jnh203.cnf
./run.sh test_data/jnh/jnh308.cnf
./run.sh test_data/jnh/jnh214.cnf
./run.sh test_data/jnh/jnh204.cnf
./run.sh test_data/jnh/jnh213.cnf
./run.sh test_data/jnh/jnh304.cnf
./run.sh test_data/jnh/jnh212.cnf
./run.sh test_data/jnh/jnh206.cnf
./run.sh test_data/jnh/jnh205.cnf
./run.sh test_data/jnh/jnh12.cnf
./run.sh test_data/jnh/jnh201.cnf
./run.sh test_data/jnh/jnh207.cnf
./run.sh test_data/jnh/jnh216.cnf
./run.sh test_data/jnh/jnh11.cnf
./run.sh test_data/jnh/jnh15.cnf
./run.sh test_data/jnh/jnh209.cnf
./run.sh test_data/jnh/jnh215.cnf
./run.sh test_data/jnh/jnh14.cnf
./run.sh test_data/jnh/jnh18.cnf
./run.sh test_data/jnh/jnh5.cnf
./run.sh test_data/jnh/jnh220.cnf
./run.sh test_data/jnh/jnh4.cnf
./run.sh test_data/jnh/jnh3.cnf
./run.sh test_data/jnh/jnh2.cnf
./run.sh test_data/jnh/jnh303.cnf
./run.sh test_data/jnh/jnh210.cnf
./run.sh test_data/jnh/jnh309.cnf
./run.sh test_data/jnh/jnh310.cnf
./run.sh test_data/jnh/jnh208.cnf
./run.sh test_data/jnh/jnh17.cnf
./run.sh test_data/jnh/jnh19.cnf
./run.sh test_data/jnh/jnh306.cnf
./run.sh test_data/jnh/jnh8.cnf
./run.sh test_data/jnh/jnh1.cnf
./run.sh test_data/jnh/jnh302.cnf
./run.sh test_data/jnh/jnh6.cnf
./run.sh test_data/jnh/jnh9.cnf
./run.sh test_data/jnh/jnh305.cnf
./run.sh test_data/jnh/jnh7.cnf
./run.sh test_data/jnh/jnh217.cnf
./run.sh test_data/jnh/jnh13.cnf
./run.sh test_data/jnh/jnh202.cnf
./run.sh test_data/jnh/jnh211.cnf
./run.sh test_data/jnh/jnh301.cnf
./run.sh test_data/jnh/jnh10.cnf
./run.sh test_data/jnh/jnh218.cnf